# Generated by Django 5.1.3 on 2025-05-08 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_cart_status_alter_cart_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='updated_at',
        ),
        migrations.AlterModelTable(
            name='cart',
            table='cart',
        ),
        migrations.AlterModelTable(
            name='cartitem',
            table='cart_item',
        ),
    ]
